apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-non-replicated
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  dataLocality: "disabled"
  dataEngine: "v1"
  disableRevisionCounter: "true"
  backupTargetName: "default"